use_frameworks!

platform :ios, '12.4'

target 'Apple-Cocoapod-KochavaUI_Example' do
  pod 'Apple-Cocoapod-KochavaUI', :path => '../'

  target 'Apple-Cocoapod-KochavaUI_Tests' do
    inherit! :search_paths

    
  end
end
